---
- hosts:
    github
  any_errors_fatal: true
  gather_facts: no
  tasks:
    - name: apply role github
      include_role:
        name: github_role
      vars:
        organization: "{{ repo.repo.split('/')[0] }}"
        reponame: "{{ repo.repo.split('/')[1] }}"
      with_items: "{{ repos }}"
      loop_control:
        loop_var: repo