---
- debug:
    msg:  "{{ repo }}"
- name: Iterate deploykeys and add them
  shell:
    executable: /bin/bash
    cmd: |
      set -x
      temp="$(tempfile)"
      echo '{{ deploy_key }}' > $temp
      message=$(gh repo deploy-key add "$temp" --allow-write -R {{ repo.repo }} 2>&1 1>/dev/null)
      rc=$?
      echo $message > /tmp/2
      echo "$rc" > /tmp/2

      if [[ "$rc" != "0" ]]; then
        if echo "$message" | grep -q "key is already in use"; then
          echo "OK"
        else
          >&2 echo "$message"
          exit -1
        fi
      fi
      rm "$temp"
      echo "DONE {{ repo.repo }}"

  loop: "{{ repo.deploy_keys is defined and repo.deploy_keys or [] }}"
  loop_control:
    loop_var: deploy_key