---

- name: set webhooks
  shell:
    executable: /bin/bash
    cmd: |
      set -x
      err="$(tempfile)"
      input_file="$(tempfile)"

      tee "$input_file" << 'EOF'
      {
        "type": "Repository",
        "name": "web",
        "active": true,
        "events": {{ webhook.events | to_nice_json }},
        "config": {
          "url": "{{ webhook.url }}",
          "content_type": "json"
        }
      }
      EOF

      cat "$input_file" | gh api /repos/{{ repo.repo }}/hooks --input - 2>"$message"
      rc=$?

      if [[ "$rc" != "0" ]]; then
        if echo "$message" | grep -q "Hook already exists"; then
          echo "OK"
        else
          >&2 echo "$message"
          exit -1
        fi
      fi
      rm "$input_file"
      echo "DONE {{ repo.repo }}"

  loop: "{{ repo.webhooks is defined and repo.webhooks or [] }}"
  loop_control:
    loop_var: webhook
