---

- name: set webhooks
  shell:
    executable: /bin/bash
    cmd: |
      set -x
      temp="$(tempfile)"

      gh api /repos/{{ repo.repo }}/hooks \
        --input - <<< '{
        "name": "web",
        "active": true,
        "events": [
          "push"
        ],
        "config": {
          "url": "{{ webhook }}",
          "content_type": "json"
        }
      }' 2>"$temp" 1>/dev/null
      rc=$?
      echo "$message"

      if [[ "$rc" != "0" ]]; then
        if echo "$message" | grep -q "key is already in use"; then
          echo "OK"
        else
          >&2 echo "$message"
          exit -1
        fi
      fi
      rm "$temp"
      echo "DONE {{ repo.repo }}"

  loop: "{{ repo.webhooks is defined and repo.webhooks or [] }}"
  loop_control:
    loop_var: webhook
